spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_fitness_tracking_application_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    jpa:
      open-in-view: false
      generate-ddl: false
      properties:
        javax:
          persistence:
            validation:
              mode: none
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
      hibernate:
        ddl-auto: validate